services:
    nginx:
        image: nginx:1.25-alpine
        container_name: nginx
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
            - .:/var/www/html
        depends_on:
            - php

    php:
        build: ./docker/php/
        container_name: php
        volumes:
            - .:/var/www/html
            - ./var/logs:/var/www/html/var/logs:rw
        environment:
            - TZ=America/Sao_Paulo
            - HANDLER=public/index.php
            - DOCUMENT_ROOT=public

    mysql:
        image: mysql:8.3
        container_name: mysql
        ports:
            - "3308:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: transfer_api
        volumes:
            - mysql-data:/var/lib/mysql
            - ./docker/mysql/init:/docker-entrypoint-initdb.d

volumes:
    mysql-data:
